apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  namespace: wordpress-tutorial # Change this
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi