apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Change this
  namespace: wordpress-tutorial # Change this
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql # Change this