apiVersion: v1
kind: Service
metadata:
  name: wordpress-service # Change this
  namespace: wordpress-tutorial # Change this
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80 # Change this
    protocol: TCP
  selector:
    app: wordpress # Change this